
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: auth-test-single
  title: Auth Test Single Login
spec:
  type: service
  parameters:
    - title: Select Environment
      required:
        - environmentType
      properties:
        environmentType:
          type: string
          title: Environment Type
          enum:
            - dev
            - test
            - prod
          default: dev
    - title: Authentication ad
      required:
        - azureAdToken
      properties:
        azureAdToken:
          type: string
          title: "azureADtoken"
          ui:field: EntraOAuthToken
          ui:options:
            scopes:
              - 'api://d96759a6-9b63-4819-b77c-d831d30c9ac6/azuread/.default'
            sessionKey: 'azuread'
            title: 'azuread'
            message: Login field for token used to access to fake azuread
    - title: Authentication backstage
      required:
        - appTokenDefault
      properties:
        appTokenDefault:
          type: string
          title: "AuthToken"
          ui:field: EntraOAuthToken
          ui:options:
            scopes:
              - 'api://d96759a6-9b63-4819-b77c-d831d30c9ac6/backstage-api-{"environmentType"}/.default'
            sessionKey: 'backstagetest{"environmentType"}'
            title: 'AuthToken'
            message: Login field for token used to access to backstage-test environment

    - title: dummy 
      required:
        - testField 
      properties:
        testField:
          type: string
          title: Select Type
          enum:
            - test1
            - test2
            - test3
          default: test1
            
  steps:
    - id: log-inventory-token
      name: Log Inventory Token
      action: log:log
      input:
        message: 'The provided inventory token is: {{ parameters.appTokenDefault}}'